// JavaScript Document
// CS258 Project 6- IIT Indore Safety and Security Website base webpage, complete with layout changes and image placeholders.-->
// Author - Mudit Maheshwari
$(document).ready(function() {

		$("#slider").show();
		$("#cso").show();
		$("#about").show();
		$("#personals").css( "display","none");
		$("#committees").css( "display","none");
		$("#institute_committee").css( "display","none");
		$("#departmental_committees").css( "display","none");
		$("#policies").css( "display","none");
		$("#chemical_safety").css( "display","none");
		$("#chemical_biowaste_disposal").css( "display","none");
		$("#fire_safety_trainings").css( "display","none");
		$("#fire_extinguishers").css( "display","none");
		$("#emergency_response").css( "display","none");
		$("#do_and_dont").css( "display","none");
		$("#lost_found").css( "display","none");
		$("#theft_report").css( "display","none");
		$("#report_crime").css( "display","none");
		$("#id_cards").css( "display","none");
		$("#alert_notice").css( "display","none");
		$("#parking").css( "display","none");
        $("#events").css( "display","none");
		$("#lost").css( "display","none");
		$("#lostandfound").css( "display","none");
		$("#found").css( "display","none");
		$("#counter").show();
		$("#quicklinks").show();
		
		$(document).on("click","#_about",function(e){
			$("#slider").show();
			$("#about").show();
			$("#cso").show();
			$("#personals").css( "display","none");
			$("#committees").css( "display","none");
			$("#institute_committee").css( "display","none");
			$("#departmental_committees").css( "display","none");
			$("#policies").css( "display","none");
			$("#chemical_safety").css( "display","none");
			$("#chemical_biowaste_disposal").css( "display","none");
			$("#fire_safety_trainings").css( "display","none");
			$("#fire_extinguishers").css( "display","none");
			$("#emergency_response").css( "display","none");
			$("#do_and_dont").css( "display","none");
			$("#lost_found").css( "display","none");
			$("#theft_report").css( "display","none");
			$("#report_crime").css( "display","none");
			$("#id_cards").css( "display","none");
			$("#alert_notice").css( "display","none");
			$("#parking").css( "display","none");
			$("#events").css( "display","none");
			$("#lost").css( "display","none");
			$("#lostandfound").css( "display","none");
			$("#found").css( "display","none");
			$("#counter").show();
			$("#quicklinks").show();
		});
		$(document).on("click","#_personals",function(e){
			$("#slider").css( "display","none");
			$("#about").css( "display","none");
			$("#cso").css( "display","none");
			$("#personals").show();
			$("#committees").css( "display","none");
			$("#institute_committee").css( "display","none");
			$("#departmental_committees").css( "display","none");
			$("#policies").css( "display","none");
			$("#chemical_safety").css( "display","none");
			$("#chemical_biowaste_disposal").css( "display","none");
			$("#fire_safety_trainings").css( "display","none");
			$("#fire_extinguishers").css( "display","none");
			$("#emergency_response").css( "display","none");
			$("#do_and_dont").css( "display","none");
			$("#lost_found").css( "display","none");
			$("#theft_report").css( "display","none");
			$("#report_crime").css( "display","none");
			$("#id_cards").css( "display","none");
			$("#alert_notice").css( "display","none");
			$("#parking").css( "display","none");
			$("#events").css( "display","none");
			$("#lost").css( "display","none");
			$("#lostandfound").css( "display","none");
			$("#found").css( "display","none");
			$("#counter").show();
			$("#quicklinks").show();
		});
		$(document).on("click","#_institute_committee",function(e){
			$("#slider").css( "display","none");
			$("#about").css( "display","none");
			$("#cso").css( "display","none");
			$("#personals").css( "display","none");
			$("#committees").css( "display","none");
			$("#institute_committee").show();
			$("#departmental_committees").css( "display","none");
			$("#policies").css( "display","none");
			$("#chemical_safety").css( "display","none");
			$("#chemical_biowaste_disposal").css( "display","none");
			$("#fire_safety_trainings").css( "display","none");
			$("#fire_extinguishers").css( "display","none");
			$("#emergency_response").css( "display","none");
			$("#do_and_dont").css( "display","none");
			$("#lost_found").css( "display","none");
			$("#theft_report").css( "display","none");
			$("#report_crime").css( "display","none");
			$("#id_cards").css( "display","none");
			$("#alert_notice").css( "display","none");
			$("#parking").css( "display","none");
			$("#events").css( "display","none");
			$("#lost").css( "display","none");
			$("#counter").show();
			$("#quicklinks").show();
			$("#lostandfound").css( "display","none");
			$("#found").css( "display","none");
			
		});
		$(document).on("click","#_departmental_committees",function(e){
			$("#slider").css( "display","none");
			$("#about").css( "display","none");
			$("#cso").css( "display","none");
			$("#personals").css( "display","none");
			$("#committees").css( "display","none");
			$("#institute_committee").css( "display","none");
			$("#departmental_committees").show();
			$("#policies").css( "display","none");
			$("#chemical_safety").css( "display","none");
			$("#chemical_biowaste_disposal").css( "display","none");
			$("#fire_safety_trainings").css( "display","none");
			$("#fire_extinguishers").css( "display","none");
			$("#emergency_response").css( "display","none");
			$("#do_and_dont").css( "display","none");
			$("#lost_found").css( "display","none");
			$("#theft_report").css( "display","none");
			$("#report_crime").css( "display","none");
			$("#id_cards").css( "display","none");
			$("#alert_notice").css( "display","none");
			$("#parking").css( "display","none");
			$("#events").css( "display","none");
			$("#lost").css( "display","none");
			$("#lostandfound").css( "display","none");
			$("#found").css( "display","none");
			$("#counter").show();
			$("#quicklinks").show();
		});
		$(document).on("click","#_policies",function(e){
			$("#slider").css( "display","none");
			$("#about").css( "display","none");
			$("#cso").css( "display","none");
			$("#personals").css( "display","none");
			$("#committees").css( "display","none");
			$("#institute_committee").css( "display","none");
			$("#departmental_committees").css( "display","none");
			$("#policies").show();
			$("#chemical_safety").css( "display","none");
			$("#chemical_biowaste_disposal").css( "display","none");
			$("#fire_safety_trainings").css( "display","none");
			$("#fire_extinguishers").css( "display","none");
			$("#emergency_response").css( "display","none");
			$("#do_and_dont").css( "display","none");
			$("#lost_found").css( "display","none");
			$("#theft_report").css( "display","none");
			$("#report_crime").css( "display","none");
			$("#id_cards").css( "display","none");
			$("#alert_notice").css( "display","none");
			$("#parking").css( "display","none");
			$("#events").css( "display","none");
			$("#lost").css( "display","none");
			$("#lostandfound").css( "display","none");
			$("#found").css( "display","none");
			$("#counter").show();
			$("#quicklinks").show();
		});
		$(document).on("click","#_chemical_safety",function(e){
			$("#slider").css( "display","none");
			$("#about").css( "display","none");
			$("#cso").css( "display","none");
			$("#personals").css( "display","none");
			$("#committees").css( "display","none");
			$("#institute_committee").css( "display","none");
			$("#departmental_committees").css( "display","none");
			$("#policies").css( "display","none");
			$("#chemical_safety").show();
			$("#chemical_biowaste_disposal").css( "display","none");
			$("#fire_safety_trainings").css( "display","none");
			$("#fire_extinguishers").css( "display","none");
			$("#emergency_response").css( "display","none");
			$("#do_and_dont").css( "display","none");
			$("#lost_found").css( "display","none");
			$("#theft_report").css( "display","none");
			$("#report_crime").css( "display","none");
			$("#id_cards").css( "display","none");
			$("#alert_notice").css( "display","none");
			$("#parking").css( "display","none");
			$("#events").css( "display","none");
			$("#lost").css( "display","none");
			$("#lostandfound").css( "display","none");
			$("#found").css( "display","none");
			$("#counter").show();
			$("#quicklinks").show();
		});
		$(document).on("click","#_chemical_biowaste_disposal",function(e){
			$("#slider").css( "display","none");
			$("#about").css( "display","none");
			$("#cso").css( "display","none");
			$("#personals").css( "display","none");
			$("#committees").css( "display","none");
			$("#institute_committee").css( "display","none");
			$("#departmental_committees").css( "display","none");
			$("#policies").css( "display","none");
			$("#chemical_safety").css( "display","none");
			$("#chemical_biowaste_disposal").show();
			$("#fire_safety_trainings").css( "display","none");
			$("#fire_extinguishers").css( "display","none");
			$("#emergency_response").css( "display","none");
			$("#do_and_dont").css( "display","none");
			$("#lost_found").css( "display","none");
			$("#theft_report").css( "display","none");
			$("#report_crime").css( "display","none");
			$("#id_cards").css( "display","none");
			$("#alert_notice").css( "display","none");
			$("#parking").css( "display","none");
			$("#events").css( "display","none");
			$("#lost").css( "display","none");
			$("#lostandfound").css( "display","none");
			$("#found").css( "display","none");
			$("#counter").show();
			$("#quicklinks").show();
		});
		$(document).on("click","#_fire_safety_trainings",function(e){
			$("#slider").css( "display","none");
			$("#about").css( "display","none");
			$("#cso").css( "display","none");
			$("#personals").css( "display","none");
			$("#committees").css( "display","none");
			$("#institute_committee").css( "display","none");
			$("#departmental_committees").css( "display","none");
			$("#policies").css( "display","none");
			$("#chemical_safety").css( "display","none");
			$("#chemical_biowaste_disposal").css( "display","none");
			$("#fire_safety_trainings").show();
			$("#fire_extinguishers").css( "display","none");
			$("#emergency_response").css( "display","none");
			$("#do_and_dont").css( "display","none");
			$("#lost_found").css( "display","none");
			$("#theft_report").css( "display","none");
			$("#report_crime").css( "display","none");
			$("#id_cards").css( "display","none");
			$("#alert_notice").css( "display","none");
			$("#parking").css( "display","none");
			$("#events").css( "display","none");
			$("#lost").css( "display","none");
			$("#lostandfound").css( "display","none");
			$("#found").css( "display","none");
			$("#counter").show();
			$("#quicklinks").show();
		});$(document).on("click","#_fire_extinguishers",function(e){
			$("#slider").css( "display","none");
			$("#about").css( "display","none");
			$("#cso").css( "display","none");
			$("#slider").css( "display","none");
			$("#front_image").css( "display","none");
			$("#right_sidebar").css( "display","none");
			$("#personals").css( "display","none");
			$("#committees").css( "display","none");
			$("#institute_committee").css( "display","none");
			$("#departmental_committees").css( "display","none");
			$("#policies").css( "display","none");
			$("#chemical_safety").css( "display","none");
			$("#chemical_biowaste_disposal").css( "display","none");
			$("#fire_safety_trainings").css( "display","none");
			$("#fire_extinguishers").show();
			$("#emergency_response").css( "display","none");
			$("#do_and_dont").css( "display","none");
			$("#lost_found").css( "display","none");
			$("#theft_report").css( "display","none");
			$("#report_crime").css( "display","none");
			$("#id_cards").css( "display","none");
			$("#alert_notice").css( "display","none");
			$("#parking").css( "display","none");
			$("#events").css( "display","none");
			$("#lost").css( "display","none");
			$("#lostandfound").css( "display","none");
			$("#found").css( "display","none");
			$("#counter").show();
			$("#quicklinks").show();
		});$(document).on("click","#_emergency_response",function(e){
			$("#slider").css( "display","none");
			$("#about").css( "display","none");
			$("#cso").css( "display","none");
			$("#personals").css( "display","none");
			$("#committees").css( "display","none");
			$("#institute_committee").css( "display","none");
			$("#departmental_committees").css( "display","none");
			$("#policies").css( "display","none");
			$("#chemical_safety").css( "display","none");
			$("#chemical_biowaste_disposal").css( "display","none");
			$("#fire_safety_trainings").css( "display","none");
			$("#fire_extinguishers").css( "display","none");
			$("#emergency_response").show();
			$("#do_and_dont").css( "display","none");
			$("#lost_found").css( "display","none");
			$("#theft_report").css( "display","none");
			$("#report_crime").css( "display","none");
			$("#id_cards").css( "display","none");
			$("#alert_notice").css( "display","none");
			$("#parking").css( "display","none");
			$("#events").css( "display","none");
			$("#lost").css( "display","none");
			$("#lostandfound").css( "display","none");
			$("#found").css( "display","none");
			$("#counter").show();
			$("#quicklinks").show();
		});
		$(document).on("click","#_do_and_dont",function(e){
			$("#slider").css( "display","none");
			$("#about").css( "display","none");
			$("#cso").css( "display","none");
			$("#slider").css( "display","none");
			$("#front_image").css( "display","none");
			$("#right_sidebar").css( "display","none");
			$("#personals").css( "display","none");
			$("#committees").css( "display","none");
			$("#institute_committee").css( "display","none");
			$("#departmental_committees").css( "display","none");
			$("#policies").css( "display","none");
			$("#chemical_safety").css( "display","none");
			$("#chemical_biowaste_disposal").css( "display","none");
			$("#fire_safety_trainings").css( "display","none");
			$("#fire_extinguishers").css( "display","none");
			$("#emergency_response").css( "display","none");
			$("#do_and_dont").show();
			$("#lost_found").css( "display","none");
			$("#theft_report").css( "display","none");
			$("#report_crime").css( "display","none");
			$("#id_cards").css( "display","none");
			$("#alert_notice").css( "display","none");
			$("#parking").css( "display","none");
			$("#events").css( "display","none");
			$("#lost").css( "display","none");
			$("#lostandfound").css( "display","none");
			$("#found").css( "display","none");
			$("#counter").show();
			$("#quicklinks").show();
		});
		$(document).on("click","#_lost_found",function(e){
			$("#slider").css( "display","none");
			$("#about").css( "display","none");
			$("#cso").css( "display","none");
			$("#personals").css( "display","none");
			$("#committees").css( "display","none");
			$("#institute_committee").css( "display","none");
			$("#departmental_committees").css( "display","none");
			$("#policies").css( "display","none");
			$("#chemical_safety").css( "display","none");
			$("#chemical_biowaste_disposal").css( "display","none");
			$("#fire_safety_trainings").css( "display","none");
			$("#fire_extinguishers").css( "display","none");
			$("#emergency_response").css( "display","none");
			$("#do_and_dont").css( "display","none");
			$("#lost_found").show();
			$("#theft_report").css( "display","none");
			$("#report_crime").css( "display","none");
			$("#id_cards").css( "display","none");
			$("#alert_notice").css( "display","none");
			$("#parking").css( "display","none");
			$("#events").css( "display","none");
			$("#lost").css( "display","none");
			$("#lostandfound").css( "display","none");
			$("#found").css( "display","none");
			$("#counter").show();
			$("#quicklinks").show();
		});
		$(document).on("click","#_theft_report",function(e){
			$("#slider").css( "display","none");
			$("#about").css( "display","none");
			$("#cso").css( "display","none");
			$("#personals").css( "display","none");
			$("#committees").css( "display","none");
			$("#institute_committee").css( "display","none");
			$("#departmental_committees").css( "display","none");
			$("#policies").css( "display","none");
			$("#chemical_safety").css( "display","none");
			$("#chemical_biowaste_disposal").css( "display","none");
			$("#fire_safety_trainings").css( "display","none");
			$("#fire_extinguishers").css( "display","none");
			$("#emergency_response").css( "display","none");
			$("#do_and_dont").css( "display","none");
			$("#lost_found").css( "display","none");
			$("#theft_report").show();
			$("#report_crime").css( "display","none");
			$("#id_cards").css( "display","none");
			$("#alert_notice").css( "display","none");
			$("#parking").css( "display","none");
			$("#events").css( "display","none");
			$("#lost").css( "display","none");
			$("#lostandfound").css( "display","none");
			$("#found").css( "display","none");
			$("#counter").show();
			$("#quicklinks").show();
		});$(document).on("click","#_report_crime",function(e){
			$("#slider").css( "display","none");
			$("#about").css( "display","none");
			$("#cso").css( "display","none");
			$("#personals").css( "display","none");
			$("#committees").css( "display","none");
			$("#institute_committee").css( "display","none");
			$("#departmental_committees").css( "display","none");
			$("#policies").css( "display","none");
			$("#chemical_safety").css( "display","none");
			$("#chemical_biowaste_disposal").css( "display","none");
			$("#fire_safety_trainings").css( "display","none");
			$("#fire_extinguishers").css( "display","none");
			$("#emergency_response").css( "display","none");
			$("#do_and_dont").css( "display","none");
			$("#lost_found").css( "display","none");
			$("#theft_report").css( "display","none");
			$("#report_crime").show();
			$("#id_cards").css( "display","none");
			$("#alert_notice").css( "display","none");
			$("#parking").css( "display","none");
			$("#events").css( "display","none");
			$("#lost").css( "display","none");
			$("#lostandfound").css( "display","none");
			$("#found").css( "display","none");
			$("#counter").show();
			$("#quicklinks").show();
		});
		$(document).on("click","#_id_cards",function(e){
			$("#slider").css( "display","none");
			$("#about").css( "display","none");
			$("#cso").css( "display","none");
			$("#personals").css( "display","none");
			$("#committees").css( "display","none");
			$("#institute_committee").css( "display","none");
			$("#departmental_committees").css( "display","none");
			$("#policies").css( "display","none");
			$("#chemical_safety").css( "display","none");
			$("#chemical_biowaste_disposal").css( "display","none");
			$("#fire_safety_trainings").css( "display","none");
			$("#fire_extinguishers").css( "display","none");
			$("#emergency_response").css( "display","none");
			$("#do_and_dont").css( "display","none");
			$("#lost_found").css( "display","none");
			$("#theft_report").css( "display","none");
			$("#report_crime").css( "display","none");
			$("#id_cards").show();
			$("#alert_notice").css( "display","none");
			$("#parking").css( "display","none");
			$("#events").css( "display","none");
			$("#lost").css( "display","none");
			$("#lostandfound").css( "display","none");
			$("#found").css( "display","none");
			$("#counter").show();
			$("#quicklinks").show();
		});
		$(document).on("click","#_alert_notice",function(e){
			$("#slider").css( "display","none");
			$("#about").css( "display","none");
			$("#cso").css( "display","none");
			$("#personals").css( "display","none");
			$("#committees").css( "display","none");
			$("#institute_committee").css( "display","none");
			$("#departmental_committees").css( "display","none");
			$("#policies").css( "display","none");
			$("#chemical_safety").css( "display","none");
			$("#chemical_biowaste_disposal").css( "display","none");
			$("#fire_safety_trainings").css( "display","none");
			$("#fire_extinguishers").css( "display","none");
			$("#emergency_response").css( "display","none");
			$("#do_and_dont").css( "display","none");
			$("#lost_found").css( "display","none");
			$("#theft_report").css( "display","none");
			$("#report_crime").css( "display","none");
			$("#id_cards").css( "display","none");
			$("#alert_notice").show();
			$("#parking").css( "display","none");
			$("#events").css( "display","none");
			$("#lost").css( "display","none");
			$("#lostandfound").css( "display","none");
			$("#found").css( "display","none");
			$("#counter").show();
			$("#quicklinks").show();
		});$(document).on("click","#_parking",function(e){
			$("#slider").css( "display","none");
			$("#about").css( "display","none");
			$("#cso").css( "display","none");
			$("#slider").css( "display","none");
			$("#front_image").css( "display","none");
			$("#right_sidebar").css( "display","none");
			$("#personals").css( "display","none");
			$("#committees").css( "display","none");
			$("#institute_committee").css( "display","none");
			$("#departmental_committees").css( "display","none");
			$("#policies").css( "display","none");
			$("#chemical_safety").css( "display","none");
			$("#chemical_biowaste_disposal").css( "display","none");
			$("#fire_safety_trainings").css( "display","none");
			$("#fire_extinguishers").css( "display","none");
			$("#emergency_response").css( "display","none");
			$("#do_and_dont").css( "display","none");
			$("#lost_found").css( "display","none");
			$("#theft_report").css( "display","none");
			$("#report_crime").css( "display","none");
			$("#id_cards").css( "display","none");
			$("#alert_notice").css( "display","none");
			$("#parking").show();
			$("#events").css( "display","none");
			$("#lost").css( "display","none");
			$("#lostandfound").css( "display","none");
			$("#found").css( "display","none");
			$("#counter").show();
			$("#quicklinks").show();
		});$(document).on("click","#_events",function(e){
			$("#slider").css( "display","none");
			$("#about").css( "display","none");
			$("#cso").css( "display","none");
			$("#personals").css( "display","none");
			$("#committees").css( "display","none");
			$("#institute_committee").css( "display","none");
			$("#departmental_committees").css( "display","none");
			$("#policies").css( "display","none");
			$("#chemical_safety").css( "display","none");
			$("#chemical_biowaste_disposal").css( "display","none");
			$("#fire_safety_trainings").css( "display","none");
			$("#fire_extinguishers").css( "display","none");
			$("#emergency_response").css( "display","none");
			$("#do_and_dont").css( "display","none");
			$("#lost_found").css( "display","none");
			$("#theft_report").css( "display","none");
			$("#report_crime").css( "display","none");
			$("#id_cards").css( "display","none");
			$("#alert_notice").css( "display","none");
			$("#parking").css( "display","none");
			$("#lostandfound").css( "display","none");
			$("#found").css( "display","none");
			$("#events").show();
			$("#lost").css( "display","none");
			$("#counter").show();
			$("#quicklinks").show();
        });$(document).on("click","#_committees",function(e){
			$("#slider").css( "display","none");
			$("#about").css( "display","none");
			$("#cso").css( "display","none");
			$("#personals").css( "display","none");
			$("#committees").show();
			$("#institute_committee").css( "display","none");
			$("#departmental_committees").css( "display","none");
			$("#policies").css( "display","none");
			$("#chemical_safety").css( "display","none");
			$("#chemical_biowaste_disposal").css( "display","none");
			$("#fire_safety_trainings").css( "display","none");
			$("#fire_extinguishers").css( "display","none");
			$("#emergency_response").css( "display","none");
			$("#do_and_dont").css( "display","none");
			$("#lost_found").css( "display","none");
			$("#theft_report").css( "display","none");
			$("#report_crime").css( "display","none");
			$("#id_cards").css( "display","none");
			$("#alert_notice").css( "display","none");
			$("#parking").css( "display","none");
			$("#events").css( "display","none");
			$("#lost").css( "display","none");
			$("#lostandfound").css( "display","none");
			$("#found").css( "display","none");
			$("#counter").show();
			$("#quicklinks").show();
        });$(document).on("click","#_lost",function(e){
			$("#slider").css( "display","none");
			$("#about").css( "display","none");
			$("#cso").css( "display","none");
			$("#personals").css( "display","none");
			$("#committees").css( "display","none");
			$("#institute_committee").css( "display","none");
			$("#departmental_committees").css( "display","none");
			$("#policies").css( "display","none");
			$("#chemical_safety").css( "display","none");
			$("#chemical_biowaste_disposal").css( "display","none");
			$("#fire_safety_trainings").css( "display","none");
			$("#fire_extinguishers").css( "display","none");
			$("#emergency_response").css( "display","none");
			$("#do_and_dont").css( "display","none");
			$("#lost_found").css( "display","none");
			$("#theft_report").css( "display","none");
			$("#report_crime").css( "display","none");
			$("#id_cards").css( "display","none");
			$("#alert_notice").css( "display","none");
			$("#parking").css( "display","none");
			$("#events").css( "display","none");
			$("#lost").show();
			$("#counter").css( "display","none");
			$("#quicklinks").css( "display","none");
			$("#lostandfound").css( "display","none");
			$("#found").css( "display","none");
			$("#events").css( "display","none");
        });$(document).on("click","#_lostandfound",function(e){
			$("#slider").css( "display","none");
			$("#about").css( "display","none");
			$("#cso").css( "display","none");
			$("#personals").css( "display","none");
			$("#committees").css( "display","none");
			$("#institute_committee").css( "display","none");
			$("#departmental_committees").css( "display","none");
			$("#policies").css( "display","none");
			$("#chemical_safety").css( "display","none");
			$("#chemical_biowaste_disposal").css( "display","none");
			$("#fire_safety_trainings").css( "display","none");
			$("#fire_extinguishers").css( "display","none");
			$("#emergency_response").css( "display","none");
			$("#do_and_dont").css( "display","none");
			$("#lost_found").css( "display","none");
			$("#theft_report").css( "display","none");
			$("#report_crime").css( "display","none");
			$("#id_cards").css( "display","none");
			$("#alert_notice").css( "display","none");
			$("#parking").css( "display","none");
			$("#events").css( "display","none");
			$("#lost").css( "display","none");
			$("#counter").css( "display","none");
			$("#quicklinks").css( "display","none");
			$("#lostandfound").show();
			$("#found").css( "display","none");
			$("#events").css( "display","none");
        });$(document).on("click","#_found",function(e){
			$("#slider").css( "display","none");
			$("#about").css( "display","none");
			$("#cso").css( "display","none");
			$("#personals").css( "display","none");
			$("#committees").css( "display","none");
			$("#institute_committee").css( "display","none");
			$("#departmental_committees").css( "display","none");
			$("#policies").css( "display","none");
			$("#chemical_safety").css( "display","none");
			$("#chemical_biowaste_disposal").css( "display","none");
			$("#fire_safety_trainings").css( "display","none");
			$("#fire_extinguishers").css( "display","none");
			$("#emergency_response").css( "display","none");
			$("#do_and_dont").css( "display","none");
			$("#lost_found").css( "display","none");
			$("#theft_report").css( "display","none");
			$("#report_crime").css( "display","none");
			$("#id_cards").css( "display","none");
			$("#alert_notice").css( "display","none");
			$("#parking").css( "display","none");
			$("#events").css( "display","none");
			$("#lost").css( "display","none");
			$("#counter").css( "display","none");
			$("#quicklinks").css( "display","none");
			$("#lostandfound").css( "display","none");
			$("#found").show();
			$("#events").css( "display","none");
               });
					
});